# Generated by Django 6.0.4 on 2026-04-20 17:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0003_servico'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='servicos', to='clientes.cliente'),
        ),
    ]
