# Generated by Django 6.0.4 on 2026-05-04 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0005_cliente_ativo'),
    ]

    operations = [
        migrations.AddField(
            model_name='servico',
            name='anexo',
            field=models.FileField(blank=True, null=True, upload_to='anexos_servicos/'),
        ),
    ]
