# Generated by Django 6.0.4 on 2026-05-11 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0006_servico_anexo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='anexo',
        ),
        migrations.CreateModel(
            name='AnexoServico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='anexos_servicos/')),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anexos', to='clientes.servico')),
            ],
        ),
    ]
